[dev]
    [dev.redis]
        ip = "4.4.32.224:2232"
        db = 0
        pass = "igera"
    [dev.mysql]
        ip = "172.21.197.14:3306"
        db = "pro"
        pass = "1234"
        user = "root"
    [dev.cache]
        ip = "47.94.3.224:1221"
        db = 0
        pass = "tigera"
    [dev.server]
        port = 8088
[online]
    [online.redis]
        ip = "1.1.1.1:9221"
        db = 0
        pass = "tigera"
    [online.mysql]
        ip = "47.24.132.124:3306"
        db = "pro"
        pass = "kkkkk"
        user = "root"
    [online.cache]
        ip = "47.94.3.224:1221"
        db = 0
        pass = "tigera"
    [online.server]
        port = 8088
